[project]
name = "lattica-studio"
version = "0.1.1"
description = "Lattica Studio"
authors = [
    {name = "LatticaAI Inc.", email = "support@lattica.ai"},
]
requires-python = ">=3.11"
dependencies = [
    "lattica-query>=2.0.0",
    "lattica-build>=0.1.1",
    "pyyaml",
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["lattica_studio*"]
exclude = ["lattica_studio.internal_demos*"]